---
abstract: 'Job-Control Webinterface for Rex'
author:
  - 'Jan Gehring <jfried@rexify.org>'
build_requires:
  Test::Mojo: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rex-JobControl
requires:
  Capture::Tiny: '0'
  Cwd: '0'
  Data::Dumper: '0'
  DateTime: '0'
  Digest::Bcrypt: '0'
  Exporter: '0'
  File::Basename: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  FindBin: '0'
  Getopt::Long: '0'
  Minion: '0'
  Mojo::Base: '0'
  Mojo::JSON: '0'
  Mojo::Log: '0'
  Mojolicious: '0'
  Mojolicious::Commands: '0'
  Mojolicious::Plugin: '0'
  Mojolicious::Plugin::Authentication: '0'
  Rex: '0'
  YAML: '0'
  base: '0'
  strict: '0'
  warnings: '0'
version: 0.7.0
